#' ringo: Read STAR files into R
#'
#' The ringo package exists for reading STAR files like those generated by
#' Relion \url{https://www2.mrc-lmb.cam.ac.uk/relion/index.php?title=Main_Page}
#' into R. This will usually be achieved by calling ringo::starr. Geddit?!
#'
#' @docType package
#' @name ringo
NULL
