#' ringo: Read STAR files into R
#'
#' The ringo package is for reading and manipulating STAR files like those generated by
#' Relion \url{https://www2.mrc-lmb.cam.ac.uk/relion/index.php?title=Main_Page}
#' into R.
#'
#' @docType package
#' @name ringo
NULL
